# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DAB.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1600, 1000)
        MainWindow.setWindowFlag(Qt.FramelessWindowHint)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
"    background-color: #161616;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetStatusBar = QtWidgets.QWidget(self.centralwidget)
        self.widgetStatusBar.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widgetStatusBar.setStyleSheet("QWidget#widgetStatusBar{\n"
"    background-color: #161616;\n"
"}")
        self.widgetStatusBar.setObjectName("widgetStatusBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetStatusBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(self.widgetStatusBar)
        self.icon.setMinimumSize(QtCore.QSize(30, 30))
        self.icon.setMaximumSize(QtCore.QSize(30, 16777215))
        self.icon.setStyleSheet("QLabel#icon{\n"
"    margin-top: 2px;\n"
"}")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/icon/icon_resources/escapeCake.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.titleLabel = QtWidgets.QLabel(self.widgetStatusBar)
        self.titleLabel.setStyleSheet("QLabel#titleLabel{\n"
"    color: white;\n"
"    font: 7pt \"微软雅黑\";\n"
"    margin-left: 0px;\n"
"    margin-right: 5px;\n"
"    margin-top: 5px;\n"
"}")
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minimizeButton = QtWidgets.QPushButton(self.widgetStatusBar)
        self.minimizeButton.setStyleSheet("QPushButton#minimizeButton {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    width: 40px;\n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton#minimizeButton:hover{\n"
"    background-color: #4D4D4D;\n"
"}")
        self.minimizeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/original/icon_resources/最小化.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon)
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.widgetStatusBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setStyleSheet("QPushButton#closeButton {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    width: 40px;\n"
"    height: 25px;\n"
"}\n"
"\n"
"QPushButton#closeButton:hover{\n"
"    background-color: #4D4D4D;\n"
"}")
        self.closeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/original/icon_resources/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon1)
        self.closeButton.setIconSize(QtCore.QSize(16, 16))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addWidget(self.widgetStatusBar)
        self.widgetMain = QtWidgets.QWidget(self.centralwidget)
        self.widgetMain.setObjectName("widgetMain")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetMain)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainMenu = QtWidgets.QWidget(self.widgetMain)
        self.mainMenu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.mainMenu.setStyleSheet("QWidget#mainMenu{\n"
"}\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    width: 45px;\n"
"    height: 45px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: #4D4D4D;\n"
"}\n"
"\n"
"QRadioButton {\n"
"    border: none;\n"
"    border-radius: 5px;\n"
"    width: 45px;\n"
"    height: 45px;\n"
"    color: rgb(255, 255, 255);\n"
"    font: 5pt \"微软雅黑\";\n"
"}\n"
"QRadioButton::indicator{\n"
"    width: 0px;\n"
"    height: 0px;\n"
"}\n"
"QRadioButton:hover{\n"
"    background-color: #4d4d4d;\n"
"}\n"
"QRadioButton:checked{\n"
"    background-color: #313131;\n"
"}\n"
"QRadioButton:checked:hover{\n"
"    background-color: #4d4d4d;\n"
"}")
        self.mainMenu.setObjectName("mainMenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainMenu)
        self.verticalLayout_2.setContentsMargins(5, 10, 0, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home = QtWidgets.QRadioButton(self.mainMenu)
        self.home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.home.setAutoFillBackground(False)
        self.home.setStyleSheet("QRadioButton{\n"
"    border-image: url(:/original/icon_resources/主页.svg);\n"
"    border-image-width: 10px;\n"
"    border-image-height: 10px;\n"
"    text: \"主页\";\n"
"}")
        self.home.setText("")
        self.home.setIconSize(QtCore.QSize(30, 30))
        self.home.setObjectName("home")
        self.verticalLayout_2.addWidget(self.home)
        self.statistics = QtWidgets.QRadioButton(self.mainMenu)
        self.statistics.setStyleSheet("border-image: url(:/original/icon_resources/统计.svg);")
        self.statistics.setText("")
        self.statistics.setIconSize(QtCore.QSize(30, 30))
        self.statistics.setChecked(False)
        self.statistics.setObjectName("statistics")
        self.verticalLayout_2.addWidget(self.statistics)
        spacerItem1 = QtWidgets.QSpacerItem(20, 318, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.radioButton = QtWidgets.QRadioButton(self.mainMenu)
        self.radioButton.setStyleSheet("border-image: url(:/original/icon_resources/设置.svg);")
        self.radioButton.setText("")
        self.radioButton.setIconSize(QtCore.QSize(30, 30))
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.horizontalLayout_2.addWidget(self.mainMenu)
        self.content = QtWidgets.QWidget(self.widgetMain)
        self.content.setStyleSheet("QWidget#content{\n"
"    background-color: #272626;\n"
"    border-radius: 10px;\n"
"    margin: 5px;\n"
"}")
        self.content.setObjectName("content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.contentStackedWidget = QtWidgets.QStackedWidget(self.content)
        self.contentStackedWidget.setStyleSheet("QStackedWidget {\n"
"    background: #272626;\n"
"    border: none;\n"
"}\n"
"QWidget {\n"
"    background: #272626;\n"
"}\n"
"QStackedWidget:tab-bar {\n"
"    /* 隐藏切页按钮 */\n"
"    visibility: hidden;\n"
"}\n"
"")
        self.contentStackedWidget.setObjectName("contentStackedWidget")
        self.home_widget = QtWidgets.QWidget()
        self.home_widget.setObjectName("home_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.home_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.home_widget)
        self.label.setStyleSheet("font: 75 12pt \"微软雅黑\";\n"
"color: white;")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.chooseType = QtWidgets.QTabWidget(self.home_widget)
        self.chooseType.setStyleSheet("\n"
"QTabWidget::pane{\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"/* 设置Tab项的样式 */\n"
"QTabBar::tab {\n"
"    background: transparent;\n"
"    border: none;\n"
"    \n"
"    font: 10pt \"微软雅黑\";\n"
"    font-size: 10px;\n"
"    color: #99BDC3;\n"
"    margin-right: 0px;\n"
"    width: 50px;\n"
"    height: 20px;\n"
"    border-radius: 3px;\n"
"    margin-right: px;\n"
"    margin-left: 0px;\n"
"    margin-top: 8px;\n"
"    margin-bottom: 8px;\n"
"}\n"
"\n"
"/* 鼠标悬停时的样式 */\n"
"QTabBar::tab:hover {\n"
"    background: #4D4D4D; /* 设置鼠标悬停时的背景色 */\n"
"}\n"
"\n"
"/* 选中Tab项的样式 */\n"
"QTabBar::tab:selected {\n"
"    margin-top: 8px; /* 设置选中Tab项不放大 */\n"
"    background-color: transparent;\n"
"    border-bottom: 2px solid #017AFF;\n"
"    color: #017AFF;\n"
"}\n"
"\n"
"QTabBar::tab:selected:hover {\n"
"    background: #4D4D4D;\n"
"}")
        self.chooseType.setTabPosition(QtWidgets.QTabWidget.North)
        self.chooseType.setObjectName("chooseType")
        self.tab = QtWidgets.QWidget()
        self.tab.setStyleSheet("background:#272626;")
        self.tab.setObjectName("tab")
        self.chooseType.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.chooseType.addTab(self.tab_2, "")
        self.verticalLayout_4.addWidget(self.chooseType)
        self.contentStackedWidget.addWidget(self.home_widget)
        self.statistic_widget = QtWidgets.QWidget()
        self.statistic_widget.setObjectName("statistic_widget")
        self.label_2 = QtWidgets.QLabel(self.statistic_widget)
        self.label_2.setGeometry(QtCore.QRect(60, 50, 54, 12))
        self.label_2.setObjectName("label_2")
        self.contentStackedWidget.addWidget(self.statistic_widget)
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label_3 = QtWidgets.QLabel(self.page)
        self.label_3.setGeometry(QtCore.QRect(190, 100, 54, 12))
        self.label_3.setObjectName("label_3")
        self.contentStackedWidget.addWidget(self.page)
        self.verticalLayout_3.addWidget(self.contentStackedWidget)
        self.horizontalLayout_2.addWidget(self.content)
        self.verticalLayout.addWidget(self.widgetMain)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.contentStackedWidget.setCurrentIndex(2)
        self.chooseType.setCurrentIndex(0)
        self.minimizeButton.clicked.connect(MainWindow.showMinimized) # type: ignore
        self.closeButton.clicked.connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "DAB"))
        self.label.setText(_translate("MainWindow", "概览"))
        self.chooseType.setTabText(self.chooseType.indexOf(self.tab), _translate("MainWindow", "杀手"))
        self.chooseType.setTabText(self.chooseType.indexOf(self.tab_2), _translate("MainWindow", "逃生者"))
        self.label_2.setText(_translate("MainWindow", "统计"))
        self.label_3.setText(_translate("MainWindow", "设置"))
import guiresources

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
