# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DAB.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, pyqtSignal

QtCore.QCoreApplication.setAttribute(Qt.AA_EnableHighDpiScaling)


def createNewItem(originalItem):
    # item_widget = QtWidgets.QListWidgetItem()
    # item_widget.setText(originItem.text())
    # root = QtWidgets.QHBoxLayout()
    # chk = QtWidgets.QCheckBox()
    # name_label = QtWidgets.QLabel(signame)
    # name_label.setObjectName('signame')
    # value_label = QtWidgets.QLabel('value')
    # value_label.setObjectName(signame + '_value')
    # root.addWidget(chk, 0, Qt.AlignLeft)
    # root.addWidget(name_label, 1, Qt.AlignLeft)
    # root.addWidget(value_label, 0, Qt.AlignRight)
    # item_widget.setLayout(root)
    return originalItem


class CustomListWidget(QtWidgets.QListWidget):
    task_data_signal = pyqtSignal(list)

    def __init__(self, parent=None):
        super(CustomListWidget, self).__init__(parent)
        self.setAcceptDrops(True)  # 开启接受拖入
        self.setDragEnabled(True)  # 开启拖拽
        self.itemClicked.connect(self._select_current_index)  # debug

    def _select_current_index(self, index):  # debug
        print('_select_current_index:', index)

    def dropEvent(self, QDropEvent):
        print('drop event occurred')  # debug
        # 获取dropEvent发生相对坐标
        pos = QDropEvent.pos()
        print('pos:', pos)  # debug
        # 获取dropEvent发生处原有item
        current_item = self.itemAt(pos)
        # 检查current_item是否存在
        if current_item == None:
            print('No Current Item!')  # debug
            # current_item不存在，dropEvent在列表空位，自动drop到列表末尾
            current_row = self.count()
        else:
            print('Current Item:', current_item.text())  # debug
            # 获取current_item信息，index为数据地址，row为行数
            current_index = self.indexFromItem(current_item)
            current_row = current_index.row()
            print('Current Row:', current_row)  # debug

        current_list = self.objectName()  # debug
        print('Current List:', current_list)  # debug
        print('self.count():', self.count())  # debug
        source_Widget = QDropEvent.source()
        print('Source List:', source_Widget.objectName())  # debug
        items = source_Widget.selectedItems()
        print('Items:', items[0])  # debug
        item = items[0]
        text = item.text()
        print('text1: ' + text)
        if not text:
            print('enter not text')
            w = source_Widget.itemWidget(item)
            label = w.findChild(QtWidgets.QLabel, 'signame')
            text = label.text()
            print('text: ' + text)
        print('didn\'t enter not text')
        row_index = source_Widget.indexFromItem(item).row()
        print(row_index)
        source_Widget.takeItem(row_index)
        self.insertItem(current_row, item)

        if self != source_Widget:
            old_item = QtWidgets.QListWidgetItem(text)
            # source_Widget.insertItem(row_index, old_item)

        print('congrats')


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1442, 900)
        MainWindow.setWindowFlag(Qt.FramelessWindowHint)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget#centralwidget{\n"
                                         "    background-color: #161616;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widgetStatusBar = QtWidgets.QWidget(self.centralwidget)
        self.widgetStatusBar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widgetStatusBar.setStyleSheet("QWidget#widgetStatusBar{\n"
                                           "    background-color: #161616;\n"
                                           "}")
        self.widgetStatusBar.setObjectName("widgetStatusBar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widgetStatusBar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(self.widgetStatusBar)
        self.icon.setMinimumSize(QtCore.QSize(50, 50))
        self.icon.setMaximumSize(QtCore.QSize(50, 50))
        self.icon.setStyleSheet("QLabel#icon{\n"
                                "    margin-top: 2px;\n"
                                "}")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap(":/icon/icon_resources/escapeCake.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.titleLabel = QtWidgets.QLabel(self.widgetStatusBar)
        self.titleLabel.setStyleSheet("QLabel#titleLabel{\n"
                                      "    color: white;\n"
                                      "    font: 16px \"微软雅黑\";\n"
                                      "    margin-left: 0px;\n"
                                      "    margin-right: 10px;\n"
                                      "    margin-top: 0px;\n"
                                      "}")
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.minimizeButton = QtWidgets.QPushButton(self.widgetStatusBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minimizeButton.sizePolicy().hasHeightForWidth())
        self.minimizeButton.setSizePolicy(sizePolicy)
        self.minimizeButton.setStyleSheet("QPushButton#minimizeButton {\n"
                                          "    border: none;\n"
                                          "    border-radius: 10px;\n"
                                          "    width: 80px;\n"
                                          "    height: 50px;\n"
                                          "}\n"
                                          "\n"
                                          "QPushButton#minimizeButton:hover{\n"
                                          "    background-color: #4D4D4D;\n"
                                          "}")
        self.minimizeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/original/icon_resources/最小化.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon)
        self.minimizeButton.setIconSize(QtCore.QSize(32, 32))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.widgetStatusBar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.closeButton.sizePolicy().hasHeightForWidth())
        self.closeButton.setSizePolicy(sizePolicy)
        self.closeButton.setStyleSheet("QPushButton#closeButton {\n"
                                       "    border: none;\n"
                                       "    border-radius: 10px;\n"
                                       "    width: 80px;\n"
                                       "    height: 50px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton#closeButton:hover{\n"
                                       "    background-color: #4D4D4D;\n"
                                       "}")
        self.closeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/original/icon_resources/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon1)
        self.closeButton.setIconSize(QtCore.QSize(32, 32))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout.addWidget(self.closeButton)
        self.verticalLayout.addWidget(self.widgetStatusBar)
        self.widgetMain = QtWidgets.QWidget(self.centralwidget)
        self.widgetMain.setObjectName("widgetMain")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetMain)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainMenu = QtWidgets.QWidget(self.widgetMain)
        self.mainMenu.setMinimumSize(QtCore.QSize(115, 0))
        self.mainMenu.setMaximumSize(QtCore.QSize(115, 16777215))
        self.mainMenu.setStyleSheet("QWidget#mainMenu{\n"
                                    "}\n"
                                    "QPushButton {\n"
                                    "    border: none;\n"
                                    "    border-radius: 5px;\n"
                                    "    width: 45px;\n"
                                    "    height: 45px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: #4D4D4D;\n"
                                    "}\n"
                                    "\n"
                                    "QRadioButton {\n"
                                    "    border: none;\n"
                                    "    border-radius: 10px;\n"
                                    "    width: 75px;\n"
                                    "    height: 75px;\n"
                                    "    color: rgb(255, 255, 255);\n"
                                    "    font: 5pt \"微软雅黑\";\n"
                                    "}\n"
                                    "QRadioButton::indicator{\n"
                                    "    width: 0px;\n"
                                    "    height: 0px;\n"
                                    "}\n"
                                    "QRadioButton:hover{\n"
                                    "    background-color: #4d4d4d;\n"
                                    "}\n"
                                    "QRadioButton:checked{\n"
                                    "    background-color: #313131;\n"
                                    "}\n"
                                    "QRadioButton:checked:hover{\n"
                                    "    background-color: #4d4d4d;\n"
                                    "}")
        self.mainMenu.setObjectName("mainMenu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.mainMenu)
        self.verticalLayout_2.setContentsMargins(20, 10, 20, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.home = QtWidgets.QRadioButton(self.mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home.sizePolicy().hasHeightForWidth())
        self.home.setSizePolicy(sizePolicy)
        self.home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.home.setAutoFillBackground(False)
        self.home.setStyleSheet("QRadioButton{\n"
                                "    border-image: url(:/original/icon_resources/主页.svg);\n"
                                "}\n"
                                "QRadioButton:checked{\n"
                                "    border-image: url(:/chosen/icon_resources/主页-选中.svg);\n"
                                "}")
        self.home.setText("")
        self.home.setIconSize(QtCore.QSize(30, 30))
        self.home.setChecked(True)
        self.home.setObjectName("home")
        self.verticalLayout_2.addWidget(self.home)
        self.statistics = QtWidgets.QRadioButton(self.mainMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statistics.sizePolicy().hasHeightForWidth())
        self.statistics.setSizePolicy(sizePolicy)
        self.statistics.setStyleSheet("QRadioButton{\n"
                                      "    border-image: url(:/original/icon_resources/统计.svg);\n"
                                      "}\n"
                                      "QRadioButton:checked{\n"
                                      "    border-image: url(:/chosen/icon_resources/统计-选中.png)\n"
                                      "}")
        self.statistics.setText("")
        self.statistics.setIconSize(QtCore.QSize(30, 30))
        self.statistics.setChecked(False)
        self.statistics.setObjectName("statistics")
        self.verticalLayout_2.addWidget(self.statistics)
        spacerItem1 = QtWidgets.QSpacerItem(20, 318, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.radioButton = QtWidgets.QRadioButton(self.mainMenu)
        self.radioButton.setStyleSheet("QRadioButton{\n"
                                       "    border-image: url(:/original/icon_resources/设置.svg);\n"
                                       "    margin-bottom: 5px\n"
                                       "}\n"
                                       "QRadioButton:checked{\n"
                                       "    border-image: url(:/chosen/icon_resources/设置选中.svg)\n"
                                       "}")
        self.radioButton.setText("")
        self.radioButton.setIconSize(QtCore.QSize(30, 30))
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.horizontalLayout_2.addWidget(self.mainMenu)
        self.content = QtWidgets.QWidget(self.widgetMain)
        self.content.setStyleSheet("QWidget#content{\n"
                                   "    background-color: #272626;\n"
                                   "    border-radius: 10px;\n"
                                   "    margin: 5px;\n"
                                   "}")
        self.content.setObjectName("content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.content)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.contentStackedWidget = QtWidgets.QStackedWidget(self.content)
        self.contentStackedWidget.setStyleSheet("QStackedWidget {\n"
                                                "    background: #272626;\n"
                                                "    border: none;\n"
                                                "}\n"
                                                "QWidget {\n"
                                                "    background: #272626;\n"
                                                "}\n"
                                                "QStackedWidget:tab-bar {\n"
                                                "    /* 隐藏切页按钮 */\n"
                                                "    visibility: hidden;\n"
                                                "}\n"
                                                "")
        self.contentStackedWidget.setObjectName("contentStackedWidget")
        self.home_widget = QtWidgets.QWidget()
        self.home_widget.setObjectName("home_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.home_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.home_widget)
        self.label.setStyleSheet("font: 75 32px \"微软雅黑\";\n"
                                 "color: white;")
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.chooseType = QtWidgets.QTabWidget(self.home_widget)
        self.chooseType.setStyleSheet("\n"
                                      "QTabWidget::pane{\n"
                                      "    border: none;\n"
                                      "}\n"
                                      "\n"
                                      "\n"
                                      "/* 设置Tab项的样式 */\n"
                                      "QTabBar::tab {\n"
                                      "    background: transparent;\n"
                                      "    border: none;\n"
                                      "    border-radius: 6px;\n"
                                      "    font: 20px \"微软雅黑\";\n"
                                      "    color: #99BDC3;\n"
                                      "    margin-right: 0px;\n"
                                      "    width: 100px;\n"
                                      "    height: 40px;\n"
                                      "    margin-right: 0px;\n"
                                      "    margin-left: 0px;\n"
                                      "    margin-top: 8px;\n"
                                      "    margin-bottom: 8px;\n"
                                      "}\n"
                                      "\n"
                                      "/* 鼠标悬停时的样式 */\n"
                                      "QTabBar::tab:hover {\n"
                                      "    background: #4D4D4D; /* 设置鼠标悬停时的背景色 */\n"
                                      "}\n"
                                      "\n"
                                      "/* 选中Tab项的样式 */\n"
                                      "QTabBar::tab:selected {\n"
                                      "    margin-top: 8px; /* 设置选中Tab项不放大 */\n"
                                      "    background-color: transparent;\n"
                                      "    border-bottom: 4px solid #017AFF;\n"
                                      "    color: #017AFF;\n"
                                      "}\n"
                                      "\n"
                                      "QTabBar::tab:selected:hover {\n"
                                      "    background: #4D4D4D;\n"
                                      "}\n"
                                      "")
        self.chooseType.setTabPosition(QtWidgets.QTabWidget.North)
        self.chooseType.setObjectName("chooseType")
        self.killerTab = QtWidgets.QWidget()
        self.killerTab.setStyleSheet("background:#272626;")
        self.killerTab.setObjectName("killerTab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.killerTab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.widget = QtWidgets.QWidget(self.killerTab)
        self.widget.setStyleSheet("Qwidget{\n"
                                  "    \n"
                                  "}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.killerList = QtWidgets.QScrollArea(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.killerList.sizePolicy().hasHeightForWidth())
        self.killerList.setSizePolicy(sizePolicy)
        self.killerList.setMinimumSize(QtCore.QSize(680, 0))
        self.killerList.setStyleSheet("QScrollArea{\n"
                                      "    border: 3px solid #4d4d4d;\n"
                                      "    border-radius: 10px;\n"
                                      "}\n"
                                      "QRadioButton {\n"
                                      "    margin: 5px;\n"
                                      "    height: 133px;\n"
                                      "    width: 127px;\n"
                                      "    border: 2px solid #4d4d4d;\n"
                                      "}\n"
                                      "QRadioButton::indicator{\n"
                                      "    width: 0px;\n"
                                      "    height: 0px;\n"
                                      "}\n"
                                      "QRadioButton:pressed {\n"
                                      "    background-color: #3d3d3d;\n"
                                      "}\n"
                                      "QRadioButton:hover{\n"
                                      "    background-color: #4d4d4d;\n"
                                      "}\n"
                                      "QRadioButton:checked{\n"
                                      "    background-color: #313131;\n"
                                      "    border: 3px solid gray;\n"
                                      "}\n"
                                      "QRadioButton:checked:hover{\n"
                                      "    background-color: #4d4d4d;\n"
                                      "}\n"
                                      "QScrollBar:vertical {\n"
                                      "    width: 8px;\n"
                                      "    background: #272626;\n"
                                      "    margin: 10px 2px 10px 1px;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar::handle:vertical {\n"
                                      "    background: gray;\n"
                                      "    border-radius: 2px;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar::handle:vertical:hover {\n"
                                      "    background: darkgray;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
                                      "    background: none;\n"
                                      "    height: 0px;\n"
                                      "    width: 0px;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                      "    background: none;\n"
                                      "}")
        self.killerList.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.killerList.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.killerList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.killerList.setWidgetResizable(True)
        self.killerList.setObjectName("killerList")
        self.killerListContent = QtWidgets.QWidget()
        self.killerListContent.setGeometry(QtCore.QRect(0, 0, 666, 1389))
        self.killerListContent.setStyleSheet("QWidget#scrollAreaWidgetContents{\n"
                                             "    \n"
                                             "}")
        self.killerListContent.setObjectName("killerListContent")
        self.gridLayout = QtWidgets.QGridLayout(self.killerListContent)
        self.gridLayout.setObjectName("gridLayout")
        self.TheCannibal = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheCannibal.sizePolicy().hasHeightForWidth())
        self.TheCannibal.setSizePolicy(sizePolicy)
        self.TheCannibal.setText("")
        self.TheCannibal.setObjectName("TheCannibal")
        self.gridLayout.addWidget(self.TheCannibal, 3, 0, 1, 1)
        self.TheHag = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheHag.sizePolicy().hasHeightForWidth())
        self.TheHag.setSizePolicy(sizePolicy)
        self.TheHag.setText("")
        self.TheHag.setObjectName("TheHag")
        self.gridLayout.addWidget(self.TheHag, 1, 1, 1, 1)
        self.TheClown = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheClown.sizePolicy().hasHeightForWidth())
        self.TheClown.setSizePolicy(sizePolicy)
        self.TheClown.setText("")
        self.TheClown.setObjectName("TheClown")
        self.gridLayout.addWidget(self.TheClown, 3, 3, 1, 1)
        self.TheHillbilly = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheHillbilly.sizePolicy().hasHeightForWidth())
        self.TheHillbilly.setSizePolicy(sizePolicy)
        self.TheHillbilly.setText("")
        self.TheHillbilly.setObjectName("TheHillbilly")
        self.gridLayout.addWidget(self.TheHillbilly, 0, 2, 1, 1)
        self.TheDeathslinger = QtWidgets.QRadioButton(self.killerListContent)
        self.TheDeathslinger.setText("")
        self.TheDeathslinger.setObjectName("TheDeathslinger")
        self.gridLayout.addWidget(self.TheDeathslinger, 5, 2, 1, 1)
        self.TheBlight = QtWidgets.QRadioButton(self.killerListContent)
        self.TheBlight.setText("")
        self.TheBlight.setObjectName("TheBlight")
        self.gridLayout.addWidget(self.TheBlight, 6, 0, 1, 1)
        self.TheShape = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheShape.sizePolicy().hasHeightForWidth())
        self.TheShape.setSizePolicy(sizePolicy)
        self.TheShape.setText("")
        self.TheShape.setObjectName("TheShape")
        self.gridLayout.addWidget(self.TheShape, 1, 0, 1, 1)
        self.TheMasterMind = QtWidgets.QRadioButton(self.killerListContent)
        self.TheMasterMind.setText("")
        self.TheMasterMind.setObjectName("TheMasterMind")
        self.gridLayout.addWidget(self.TheMasterMind, 8, 0, 1, 1)
        self.TheSpirit = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheSpirit.sizePolicy().hasHeightForWidth())
        self.TheSpirit.setSizePolicy(sizePolicy)
        self.TheSpirit.setText("")
        self.TheSpirit.setObjectName("TheSpirit")
        self.gridLayout.addWidget(self.TheSpirit, 4, 0, 1, 1)
        self.ThePig = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThePig.sizePolicy().hasHeightForWidth())
        self.ThePig.setSizePolicy(sizePolicy)
        self.ThePig.setText("")
        self.ThePig.setObjectName("ThePig")
        self.gridLayout.addWidget(self.ThePig, 3, 2, 1, 1)
        self.TheSkullMerchant = QtWidgets.QRadioButton(self.killerListContent)
        self.TheSkullMerchant.setText("")
        self.TheSkullMerchant.setObjectName("TheSkullMerchant")
        self.gridLayout.addWidget(self.TheSkullMerchant, 8, 2, 1, 1)
        self.TheOni = QtWidgets.QRadioButton(self.killerListContent)
        self.TheOni.setText("")
        self.TheOni.setObjectName("TheOni")
        self.gridLayout.addWidget(self.TheOni, 5, 1, 1, 1)
        self.TheKnight = QtWidgets.QRadioButton(self.killerListContent)
        self.TheKnight.setText("")
        self.TheKnight.setObjectName("TheKnight")
        self.gridLayout.addWidget(self.TheKnight, 8, 1, 1, 1)
        self.TheTwins = QtWidgets.QRadioButton(self.killerListContent)
        self.TheTwins.setText("")
        self.TheTwins.setObjectName("TheTwins")
        self.gridLayout.addWidget(self.TheTwins, 6, 1, 1, 1)
        self.TheNurse = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheNurse.sizePolicy().hasHeightForWidth())
        self.TheNurse.setSizePolicy(sizePolicy)
        self.TheNurse.setText("")
        self.TheNurse.setObjectName("TheNurse")
        self.gridLayout.addWidget(self.TheNurse, 0, 3, 1, 1)
        self.TheSingularity = QtWidgets.QRadioButton(self.killerListContent)
        self.TheSingularity.setText("")
        self.TheSingularity.setObjectName("TheSingularity")
        self.gridLayout.addWidget(self.TheSingularity, 8, 3, 1, 1)
        self.TheYerkes = QtWidgets.QRadioButton(self.killerListContent)
        self.TheYerkes.setText("")
        self.TheYerkes.setObjectName("TheYerkes")
        self.gridLayout.addWidget(self.TheYerkes, 9, 1, 1, 1)
        self.TheLegion = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheLegion.sizePolicy().hasHeightForWidth())
        self.TheLegion.setSizePolicy(sizePolicy)
        self.TheLegion.setText("")
        self.TheLegion.setObjectName("TheLegion")
        self.gridLayout.addWidget(self.TheLegion, 4, 1, 1, 1)
        self.TheExecutioner = QtWidgets.QRadioButton(self.killerListContent)
        self.TheExecutioner.setText("")
        self.TheExecutioner.setObjectName("TheExecutioner")
        self.gridLayout.addWidget(self.TheExecutioner, 5, 3, 1, 1)
        self.TheArtist = QtWidgets.QRadioButton(self.killerListContent)
        self.TheArtist.setText("")
        self.TheArtist.setObjectName("TheArtist")
        self.gridLayout.addWidget(self.TheArtist, 7, 1, 1, 1)
        self.TheXenomorph = QtWidgets.QRadioButton(self.killerListContent)
        self.TheXenomorph.setText("")
        self.TheXenomorph.setObjectName("TheXenomorph")
        self.gridLayout.addWidget(self.TheXenomorph, 9, 0, 1, 1)
        self.TheCenobite = QtWidgets.QRadioButton(self.killerListContent)
        self.TheCenobite.setText("")
        self.TheCenobite.setObjectName("TheCenobite")
        self.gridLayout.addWidget(self.TheCenobite, 7, 0, 1, 1)
        self.TheNemesis = QtWidgets.QRadioButton(self.killerListContent)
        self.TheNemesis.setText("")
        self.TheNemesis.setObjectName("TheNemesis")
        self.gridLayout.addWidget(self.TheNemesis, 6, 3, 1, 1)
        self.ThePlague = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ThePlague.sizePolicy().hasHeightForWidth())
        self.ThePlague.setSizePolicy(sizePolicy)
        self.ThePlague.setText("")
        self.ThePlague.setObjectName("ThePlague")
        self.gridLayout.addWidget(self.ThePlague, 4, 2, 1, 1)
        self.TheDemogorgon = QtWidgets.QRadioButton(self.killerListContent)
        self.TheDemogorgon.setText("")
        self.TheDemogorgon.setObjectName("TheDemogorgon")
        self.gridLayout.addWidget(self.TheDemogorgon, 5, 0, 1, 1)
        self.TheNightmare = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheNightmare.sizePolicy().hasHeightForWidth())
        self.TheNightmare.setSizePolicy(sizePolicy)
        self.TheNightmare.setText("")
        self.TheNightmare.setObjectName("TheNightmare")
        self.gridLayout.addWidget(self.TheNightmare, 3, 1, 1, 1)
        self.TheTrapper = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheTrapper.sizePolicy().hasHeightForWidth())
        self.TheTrapper.setSizePolicy(sizePolicy)
        self.TheTrapper.setStyleSheet("")
        self.TheTrapper.setText("")
        self.TheTrapper.setObjectName("TheTrapper")
        self.gridLayout.addWidget(self.TheTrapper, 0, 0, 1, 1)
        self.TheOnryo = QtWidgets.QRadioButton(self.killerListContent)
        self.TheOnryo.setText("")
        self.TheOnryo.setObjectName("TheOnryo")
        self.gridLayout.addWidget(self.TheOnryo, 7, 2, 1, 1)
        self.TheGhostface = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheGhostface.sizePolicy().hasHeightForWidth())
        self.TheGhostface.setSizePolicy(sizePolicy)
        self.TheGhostface.setText("")
        self.TheGhostface.setObjectName("TheGhostface")
        self.gridLayout.addWidget(self.TheGhostface, 4, 3, 1, 1)
        self.TheTrickster = QtWidgets.QRadioButton(self.killerListContent)
        self.TheTrickster.setText("")
        self.TheTrickster.setObjectName("TheTrickster")
        self.gridLayout.addWidget(self.TheTrickster, 6, 2, 1, 1)
        self.TheHuntress = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheHuntress.sizePolicy().hasHeightForWidth())
        self.TheHuntress.setSizePolicy(sizePolicy)
        self.TheHuntress.setText("")
        self.TheHuntress.setObjectName("TheHuntress")
        self.gridLayout.addWidget(self.TheHuntress, 1, 3, 1, 1)
        self.TheDredge = QtWidgets.QRadioButton(self.killerListContent)
        self.TheDredge.setStyleSheet("")
        self.TheDredge.setText("")
        self.TheDredge.setObjectName("TheDredge")
        self.gridLayout.addWidget(self.TheDredge, 7, 3, 1, 1)
        self.TheUnknown = QtWidgets.QRadioButton(self.killerListContent)
        self.TheUnknown.setText("")
        self.TheUnknown.setObjectName("TheUnknown")
        self.gridLayout.addWidget(self.TheUnknown, 9, 2, 1, 1)
        self.TheWraith = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheWraith.sizePolicy().hasHeightForWidth())
        self.TheWraith.setSizePolicy(sizePolicy)
        self.TheWraith.setText("")
        self.TheWraith.setObjectName("TheWraith")
        self.gridLayout.addWidget(self.TheWraith, 0, 1, 1, 1)
        self.TheDoctor = QtWidgets.QRadioButton(self.killerListContent)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TheDoctor.sizePolicy().hasHeightForWidth())
        self.TheDoctor.setSizePolicy(sizePolicy)
        self.TheDoctor.setText("")
        self.TheDoctor.setObjectName("TheDoctor")
        self.gridLayout.addWidget(self.TheDoctor, 1, 2, 1, 1)
        self.killerList.setWidget(self.killerListContent)
        self.horizontalLayout_4.addWidget(self.killerList)
        self.killerListArea = QtWidgets.QWidget(self.widget)
        self.killerListArea.setStyleSheet("")
        self.killerListArea.setObjectName("killerListArea")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.killerListArea)
        self.verticalLayout_5.setContentsMargins(9, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.mainChooseFrame = QtWidgets.QWidget(self.killerListArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainChooseFrame.sizePolicy().hasHeightForWidth())
        self.mainChooseFrame.setSizePolicy(sizePolicy)
        self.mainChooseFrame.setObjectName("mainChooseFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.mainChooseFrame)
        self.horizontalLayout_7.setContentsMargins(-1, 0, 0, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.chooseSearchFrame = QtWidgets.QWidget(self.mainChooseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseSearchFrame.sizePolicy().hasHeightForWidth())
        self.chooseSearchFrame.setSizePolicy(sizePolicy)
        self.chooseSearchFrame.setMinimumSize(QtCore.QSize(274, 0))
        self.chooseSearchFrame.setMaximumSize(QtCore.QSize(274, 16777215))
        self.chooseSearchFrame.setStyleSheet("QWidget#chooseSearchFrame {\n"
                                             "    width: 277;\n"
                                             "}")
        self.chooseSearchFrame.setObjectName("chooseSearchFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.chooseSearchFrame)
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.killerTargetType = QtWidgets.QComboBox(self.chooseSearchFrame)
        self.killerTargetType.setAutoFillBackground(False)
        self.killerTargetType.setStyleSheet("QComboBox{\n"
                                            "    height: 36px;\n"
                                            "    color: #99bdc3;\n"
                                            "    font: 21px \"微软雅黑\";\n"
                                            "    border: 2px solid #4d4d4d;\n"
                                            "    border-bottom: 1px solid #4d4d4d;\n"
                                            "    border-top-left-radius: 10px;  /* 左上角 */\n"
                                            "    border-top-right-radius: 10px;  /* 右上角 */\n"
                                            "    border-bottom-right-radius: 0px;  /* 右下角 */\n"
                                            "    border-bottom-left-radius: 0px;  /* 左下角 */\n"
                                            "    margin-top: 0px;\n"
                                            "    margin-bottom: 0px;\n"
                                            "    padding-left: 6px;\n"
                                            "}\n"
                                            "QComboBox:hover{\n"
                                            "    border: 2px solid #8a8a8a;\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox::drop-down{\n"
                                            "    border-image: url(:/icon/icon_resources/下拉箭头.svg);\n"
                                            "    width: 22px;\n"
                                            "    height: 22px;\n"
                                            "    margin-top: 9px;\n"
                                            "    margin-right: 10px;\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox QAbstractItemView{\n"
                                            "    border: 2px solid #8a8a8a;\n"
                                            "    border-top: 1px solid #8a8a8a;\n"
                                            "    border-top-left-radius: 0px;  /* 左上角 */\n"
                                            "    border-top-right-radius: 0px;  /* 右上角 */\n"
                                            "    border-bottom-right-radius: 10px;  /* 右下角 */\n"
                                            "    border-bottom-left-radius: 10px;  /* 左下角 */\n"
                                            "    outline: none;\n"
                                            "    color: #cccccc;\n"
                                            "    font: 21px \"微软雅黑\";\n"
                                            "    background: #272626;\n"
                                            "    padding: 12px 6px 12px 6px;\n"
                                            "}\n"
                                            "\n"
                                            "QComboBox QAbstractItemView::item{\n"
                                            "    border: none;\n"
                                            "    outline: none;\n"
                                            "    height: 36px;\n"
                                            "    border-radius: 10px;\n"
                                            "    background: #272626;\n"
                                            "}\n"
                                            "QComboBox QAbstractItemView::item:selected{\n"
                                            "    border-radius: 10px;\n"
                                            "    background: #313131;\n"
                                            "}\n"
                                            "QComboBox QAbstractItemView::item:hover{\n"
                                            "    border-radius: 10px;\n"
                                            "    background: #4D4D4D;\n"
                                            "}")
        self.killerTargetType.setFrame(True)
        self.killerTargetType.setObjectName("killerTargetType")
        self.killerTargetType.addItem("")
        self.killerTargetType.addItem("")
        self.killerTargetType.addItem("")
        self.verticalLayout_7.addWidget(self.killerTargetType)
        self.searchKillerItem = QtWidgets.QLineEdit(self.chooseSearchFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchKillerItem.sizePolicy().hasHeightForWidth())
        self.searchKillerItem.setSizePolicy(sizePolicy)
        self.searchKillerItem.setStyleSheet("QLineEdit {\n"
                                            "    height: 36px;\n"
                                            "    margin-bottom: 0px;\n"
                                            "    border: 2px solid #4d4d4d;\n"
                                            "    border-top: 1px solid #4d4d4d;\n"
                                            "    border-bottom: 1px solid #4d4d4d;\n"
                                            "    color: #99bdc3;\n"
                                            "    font: 21px \"微软雅黑\";\n"
                                            "    padding-left: 6px;\n"
                                            "    padding-right: 6px;\n"
                                            "}\n"
                                            "\n"
                                            "QLineEdit:hover {\n"
                                            "    border-color: #8a8a8a\n"
                                            "}")
        self.searchKillerItem.setInputMask("")
        self.searchKillerItem.setText("")
        self.searchKillerItem.setObjectName("searchKillerItem")
        self.verticalLayout_7.addWidget(self.searchKillerItem)
        self.killerChooseList = CustomListWidget(self.chooseSearchFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.killerChooseList.sizePolicy().hasHeightForWidth())
        self.killerChooseList.setSizePolicy(sizePolicy)
        self.killerChooseList.setStyleSheet("QListWidget{\n"
                                            "    border: 2px solid #4d4d4d;\n"
                                            "    border-top: 1px solid #4d4d4d;\n"
                                            "    border-top-left-radius: 0px;  /* 左上角 */\n"
                                            "    border-top-right-radius: 0px;  /* 右上角 */\n"
                                            "    border-bottom-right-radius: 10px;  /* 右下角 */\n"
                                            "    border-bottom-left-radius: 10px;  /* 左下角 */\n"
                                            "    margin-top: 0px;\n"
                                            "    padding: 10px 5px 10px 5px;\n"
                                            "}\n"
                                            "\n"
                                            "\n"
                                            "QListWidget:focus {\n"
                                            "    outline: none;\n"
                                            "}\n"
                                            "QListWidget::dropIndicator {\n"
                                            "    color: #3d3d3d;\n"
                                            "}\n"
                                            "QListWidget::item{\n"
                                            "    color: #99bdc3;\n"
                                            "    height: 80px;\n"
                                            "    margin-bottom: 5px;\n"
                                            "    margin-top: 5px;\n"
                                            "    border-radius: 10px;\n"
                                            "    border: 1px solid #4d4d4d;\n"
                                            "    opacity: 0.5;\n"
                                            "    padding-left: 20px;\n"
                                            "}\n"
                                            "QListWidget::item:hover {\n"
                                            "    background: #4d4d4d;\n"
                                            "}\n"
                                            "\n"
                                            "/*QListWidget::item:selected {\n"
                                            "    border-radius: 10px;\n"
                                            "    border: 1px solid #808080;\n"
                                            "    background: #313131;\n"
                                            "}*/\n"
                                            "\n"
                                            "QScrollBar:vertical {\n"
                                            "    width: 7px;\n"
                                            "    background: #272626;\n"
                                            "    margin: 10px 0px 10px 3px;\n"
                                            "    border-radius: 2px;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar::handle:vertical {\n"
                                            "    background: gray;\n"
                                            "    border-radius: 2px;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar::handle:vertical:hover {\n"
                                            "    background: darkgray;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
                                            "    background: none;\n"
                                            "    height: 0px;\n"
                                            "    width: 0px;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                            "    background: none;\n"
                                            "}")
        self.killerChooseList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.killerChooseList.setDragEnabled(True)
        self.killerChooseList.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.killerChooseList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.killerChooseList.setIconSize(QtCore.QSize(80, 80))
        self.killerChooseList.setTextElideMode(QtCore.Qt.ElideLeft)
        self.killerChooseList.setObjectName("killerChooseList")
        self.verticalLayout_7.addWidget(self.killerChooseList)
        self.horizontalLayout_7.addWidget(self.chooseSearchFrame)
        self.targetFrame = QtWidgets.QWidget(self.mainChooseFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.targetFrame.sizePolicy().hasHeightForWidth())
        self.targetFrame.setSizePolicy(sizePolicy)
        self.targetFrame.setMinimumSize(QtCore.QSize(274, 0))
        self.targetFrame.setMaximumSize(QtCore.QSize(274, 16777215))
        self.targetFrame.setStyleSheet("QWidget#targetFrame {\n"
                                       "    width: 277;\n"
                                       "}")
        self.targetFrame.setObjectName("targetFrame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.targetFrame)
        self.verticalLayout_6.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.chooseTargetHint = QtWidgets.QLabel(self.targetFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chooseTargetHint.sizePolicy().hasHeightForWidth())
        self.chooseTargetHint.setSizePolicy(sizePolicy)
        self.chooseTargetHint.setMinimumSize(QtCore.QSize(0, 38))
        self.chooseTargetHint.setStyleSheet("font: 9pt \"微软雅黑\";\n"
                                            "color: #99bdc3;\n"
                                            "height: 50px;\n"
                                            "\n"
                                            "border-top-left-radius: 10px;  /* 左上角 */\n"
                                            "border-top-right-radius: 10px;  /* 右上角 */\n"
                                            "border-bottom-right-radius: 0px;  /* 右下角 */\n"
                                            "border-bottom-left-radius: 0px;  /* 左下角 */\n"
                                            "border: 2px solid #4d4d4d;\n"
                                            "border-bottom: 1px solid #4d4d4d;")
        self.chooseTargetHint.setObjectName("chooseTargetHint")
        self.verticalLayout_6.addWidget(self.chooseTargetHint)
        self.killerTargetList = CustomListWidget(self.targetFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.killerTargetList.sizePolicy().hasHeightForWidth())
        self.killerTargetList.setSizePolicy(sizePolicy)
        self.killerTargetList.setStyleSheet("QListWidget{\n"
                                            "    border: 2px solid #4d4d4d;\n"
                                            "    border-top: 1px solid #4d4d4d;\n"
                                            "    border-bottom: 1px solid #4d4d4d;\n"
                                            "    padding: 10px 5px 10px 5px;\n"
                                            "}\n"
                                            "\n"
                                            "QListWidget:focus {\n"
                                            "    outline: none;\n"
                                            "}\n"
                                            "QListWidget::dropIndicator {\n"
                                            "    color: #3d3d3d;\n"
                                            "}\n"
                                            "QListWidget::item{\n"
                                            "    color: #99bdc3;\n"
                                            "    height: 80px;\n"
                                            "    margin-bottom: 5px;\n"
                                            "    margin-top: 5px;\n"
                                            "    border-radius: 10px;\n"
                                            "    border: 1px solid #4d4d4d;\n"
                                            "    opacity: 0.5;\n"
                                            "    padding-left: 20px;\n"
                                            "}\n"
                                            "QListWidget::item:hover {\n"
                                            "    background: #4d4d4d;\n"
                                            "}\n"
                                            "\n"
                                            "QListWidget::item:selected {\n"
                                            "    border-radius: 10px;\n"
                                            "    border: 1px solid #808080;\n"
                                            "    background: #313131;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar:vertical {\n"
                                            "    width: 7px;\n"
                                            "    background: #272626;\n"
                                            "    margin: 10px 0px 10px 3px;\n"
                                            "    border-radius: 2px;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar::handle:vertical {\n"
                                            "    background: gray;\n"
                                            "    border-radius: 2px;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar::handle:vertical:hover {\n"
                                            "    background: darkgray;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
                                            "    background: none;\n"
                                            "    height: 0px;\n"
                                            "    width: 0px;\n"
                                            "}\n"
                                            "\n"
                                            "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                            "    background: none;\n"
                                            "}")
        self.killerTargetList.setDragEnabled(True)
        self.killerTargetList.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.killerTargetList.setDefaultDropAction(QtCore.Qt.MoveAction)
        self.killerTargetList.setIconSize(QtCore.QSize(80, 80))
        self.killerTargetList.setObjectName("killerTargetList")
        self.verticalLayout_6.addWidget(self.killerTargetList)
        self.emptyTargetButtom = QtWidgets.QPushButton(self.targetFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.emptyTargetButtom.sizePolicy().hasHeightForWidth())
        self.emptyTargetButtom.setSizePolicy(sizePolicy)
        self.emptyTargetButtom.setStyleSheet("QPushButton{\n"
                                             "    height: 36px;\n"
                                             "\n"
                                             "    border-top-left-radius: 0px;  /* 左上角 */\n"
                                             "    border-top-right-radius: 0px;  /* 右上角 */\n"
                                             "    border-bottom-right-radius: 10px;  /* 右下角 */\n"
                                             "    border-bottom-left-radius: 10px;  /* 左下角 */\n"
                                             "    border: 2px solid #4d4d4d;\n"
                                             "    border-top: 1px solid #4d4d4d;\n"
                                             "    font: 21px \"微软雅黑\";\n"
                                             "    color: #99BDC3;\n"
                                             "    margin-top: 0px;\n"
                                             "    margin-bottom: 0px;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover{\n"
                                             "    background: #4d4d4d;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed{\n"
                                             "    background: #3d3d3d\n"
                                             "}")
        self.emptyTargetButtom.setObjectName("emptyTargetButtom")
        self.verticalLayout_6.addWidget(self.emptyTargetButtom)
        self.horizontalLayout_7.addWidget(self.targetFrame)
        self.verticalLayout_5.addWidget(self.mainChooseFrame)
        self.killerStart = QtWidgets.QPushButton(self.killerListArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.killerStart.sizePolicy().hasHeightForWidth())
        self.killerStart.setSizePolicy(sizePolicy)
        self.killerStart.setStyleSheet("QPushButton{\n"
                                       "    height: 60px;\n"
                                       "    width: 120px;\n"
                                       "    border-radius: 10px;\n"
                                       "    border: 2px solid #4d4d4d;\n"
                                       "    font: 25px \"微软雅黑\";\n"
                                       "    color: #99BDC3;\n"
                                       "    margin-top: 20px;\n"
                                       "    margin-bottom: 0px;\n"
                                       "    width: 200px;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:hover{\n"
                                       "    background: #4d4d4d;\n"
                                       "}\n"
                                       "\n"
                                       "QPushButton:pressed{\n"
                                       "    background: #3d3d3d\n"
                                       "}")
        self.killerStart.setObjectName("killerStart")
        self.verticalLayout_5.addWidget(self.killerStart, 0, QtCore.Qt.AlignHCenter)
        self.killerStopHint = QtWidgets.QLabel(self.killerListArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.killerStopHint.sizePolicy().hasHeightForWidth())
        self.killerStopHint.setSizePolicy(sizePolicy)
        self.killerStopHint.setStyleSheet("QLabel{\n"
                                          "    margin-left: 20px;\n"
                                          "    margin-right: 20px;\n"
                                          "    color: #5d5d5d;\n"
                                          "    font: 16px \"微软雅黑\";\n"
                                          "}")
        self.killerStopHint.setTextFormat(QtCore.Qt.AutoText)
        self.killerStopHint.setAlignment(QtCore.Qt.AlignCenter)
        self.killerStopHint.setObjectName("killerStopHint")
        self.verticalLayout_5.addWidget(self.killerStopHint)
        self.horizontalLayout_4.addWidget(self.killerListArea)
        self.horizontalLayout_3.addWidget(self.widget)
        self.chooseType.addTab(self.killerTab, "")
        self.survivorTab = QtWidgets.QWidget()
        self.survivorTab.setObjectName("survivorTab")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.survivorTab)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.survivorTargetArea = QtWidgets.QWidget(self.survivorTab)
        self.survivorTargetArea.setMaximumSize(QtCore.QSize(400, 16777215))
        self.survivorTargetArea.setObjectName("survivorTargetArea")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.survivorTargetArea)
        self.verticalLayout_9.setContentsMargins(9, 0, -1, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.survivorTargetList = QtWidgets.QScrollArea(self.survivorTargetArea)
        self.survivorTargetList.setMinimumSize(QtCore.QSize(380, 0))
        self.survivorTargetList.setStyleSheet("QScrollArea{\n"
                                              "    border: 3px solid #4d4d4d;\n"
                                              "    border-radius: 10px;\n"
                                              "}\n"
                                              "QScrollArea:QWidget{\n"
                                              "    border: none;\n"
                                              "    border-radius: 20px;\n"
                                              "    background: #272626;\n"
                                              "}\n"
                                              "\n"
                                              "QScrollBar:vertical {\n"
                                              "    width: 8px;\n"
                                              "    background: #272626;\n"
                                              "    margin: 10px 0px 10px 3px;\n"
                                              "    border-radius: 4px;\n"
                                              "}\n"
                                              "\n"
                                              "QScrollBar::handle:vertical {\n"
                                              "    background: gray;\n"
                                              "    border-radius: 2px;\n"
                                              "}\n"
                                              "\n"
                                              "QScrollBar::handle:vertical:hover {\n"
                                              "    background: darkgray;\n"
                                              "}\n"
                                              "\n"
                                              "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
                                              "    background: none;\n"
                                              "    height: 0px;\n"
                                              "    width: 0px;\n"
                                              "}\n"
                                              "\n"
                                              "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                              "    background: none;\n"
                                              "}")
        self.survivorTargetList.setWidgetResizable(True)
        self.survivorTargetList.setObjectName("survivorTargetList")
        self.survivorTargetContent = QtWidgets.QWidget()
        self.survivorTargetContent.setGeometry(QtCore.QRect(0, 0, 366, 18))
        self.survivorTargetContent.setObjectName("survivorTargetContent")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.survivorTargetContent)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        spacerItem3 = QtWidgets.QSpacerItem(20, 571, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.survivorTargetList.setWidget(self.survivorTargetContent)
        self.verticalLayout_9.addWidget(self.survivorTargetList)
        self.addSurvivorTarget = QtWidgets.QPushButton(self.survivorTargetArea)
        self.addSurvivorTarget.setStyleSheet("QPushButton{\n"
                                             "    height: 60px;\n"
                                             "    border-radius: 10px;\n"
                                             "    border: 2px solid #4d4d4d;\n"
                                             "    font: 20pt \"微软雅黑\";\n"
                                             "    color: #99BDC3;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover{\n"
                                             "    background: #4d4d4d;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed{\n"
                                             "    background: #3d3d3d\n"
                                             "}")
        self.addSurvivorTarget.setObjectName("addSurvivorTarget")
        self.verticalLayout_9.addWidget(self.addSurvivorTarget)
        self.horizontalLayout_6.addWidget(self.survivorTargetArea)
        self.survivorStartArea = QtWidgets.QWidget(self.survivorTab)
        self.survivorStartArea.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.survivorStartArea.setAutoFillBackground(False)
        self.survivorStartArea.setObjectName("survivorStartArea")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.survivorStartArea)
        self.verticalLayout_8.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem4)
        self.survivorStart = QtWidgets.QPushButton(self.survivorStartArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.survivorStart.sizePolicy().hasHeightForWidth())
        self.survivorStart.setSizePolicy(sizePolicy)
        self.survivorStart.setStyleSheet("QPushButton{\n"
                                         "    height: 60px;\n"
                                         "    width: 150px;\n"
                                         "    border-radius: 10px;\n"
                                         "    border: 2px solid #4d4d4d;\n"
                                         "    font: 20pt \"微软雅黑\";\n"
                                         "    color: #99BDC3;\n"
                                         "    margin: 20px;\n"
                                         "    margin-bottom: 0px;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:hover{\n"
                                         "    background: #4d4d4d;\n"
                                         "}\n"
                                         "\n"
                                         "QPushButton:pressed{\n"
                                         "    background: #3d3d3d\n"
                                         "}")
        self.survivorStart.setObjectName("survivorStart")
        self.verticalLayout_8.addWidget(self.survivorStart)
        self.survivorStopHint = QtWidgets.QLabel(self.survivorStartArea)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.survivorStopHint.sizePolicy().hasHeightForWidth())
        self.survivorStopHint.setSizePolicy(sizePolicy)
        self.survivorStopHint.setStyleSheet("QLabel{\n"
                                            "    margin-left: 20px;\n"
                                            "    margin-right: 20px;\n"
                                            "    color: #5d5d5d;\n"
                                            "    font: 12pt \"微软雅黑\";\n"
                                            "}")
        self.survivorStopHint.setTextFormat(QtCore.Qt.AutoText)
        self.survivorStopHint.setAlignment(QtCore.Qt.AlignCenter)
        self.survivorStopHint.setObjectName("survivorStopHint")
        self.verticalLayout_8.addWidget(self.survivorStopHint)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem5)
        self.horizontalLayout_6.addWidget(self.survivorStartArea)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.chooseType.addTab(self.survivorTab, "")
        self.verticalLayout_4.addWidget(self.chooseType)
        self.contentStackedWidget.addWidget(self.home_widget)
        self.statistic_widget = QtWidgets.QWidget()
        self.statistic_widget.setObjectName("statistic_widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.statistic_widget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.developingButton = QtWidgets.QPushButton(self.statistic_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.developingButton.sizePolicy().hasHeightForWidth())
        self.developingButton.setSizePolicy(sizePolicy)
        self.developingButton.setStyleSheet("QPushButton{\n"
                                            "    height: 100px;\n"
                                            "    width: 450px;\n"
                                            "    border-radius: 10px;\n"
                                            "    border: 2px solid #4d4d4d;\n"
                                            "    font: 25px \"微软雅黑\";\n"
                                            "    color: #99BDC3;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:hover{\n"
                                            "    background: #4d4d4d;\n"
                                            "}\n"
                                            "\n"
                                            "QPushButton:pressed{\n"
                                            "    background: #3d3d3d\n"
                                            "}")
        self.developingButton.setObjectName("developingButton")
        self.horizontalLayout_5.addWidget(self.developingButton)
        self.contentStackedWidget.addWidget(self.statistic_widget)
        self.settings_widget = QtWidgets.QWidget()
        self.settings_widget.setObjectName("settings_widget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.settings_widget)
        self.verticalLayout_11.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_11.setSpacing(9)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.settings = QtWidgets.QLabel(self.settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settings.sizePolicy().hasHeightForWidth())
        self.settings.setSizePolicy(sizePolicy)
        self.settings.setStyleSheet("font: 75 48px \"微软雅黑\";\n"
                                    "color: white;")
        self.settings.setObjectName("settings")
        self.verticalLayout_11.addWidget(self.settings)
        self.scrollArea = QtWidgets.QScrollArea(self.settings_widget)
        self.scrollArea.setStyleSheet("QScrollArea{\n"
                                      "    border: 3px solid #4d4d4d;\n"
                                      "    border-radius: 10px;\n"
                                      "}\n"
                                      "QScrollArea:QWidget{\n"
                                      "    border: none;\n"
                                      "    background: #272626;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar:vertical {\n"
                                      "    width: 8px;\n"
                                      "    background: #272626;\n"
                                      "    margin: 10px 2px 10px 1px;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar::handle:vertical {\n"
                                      "    background: gray;\n"
                                      "    border-radius: 2px;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar::handle:vertical:hover {\n"
                                      "    background: darkgray;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
                                      "    background: none;\n"
                                      "    height: 0px;\n"
                                      "    width: 0px;\n"
                                      "}\n"
                                      "\n"
                                      "QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
                                      "    background: none;\n"
                                      "}")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 241, 152))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setStyleSheet("\n"
                                   "    font: 32px \"微软雅黑\";\n"
                                   "    color: #99BDC3;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        self.gameDirComboBox = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gameDirComboBox.sizePolicy().hasHeightForWidth())
        self.gameDirComboBox.setSizePolicy(sizePolicy)
        self.gameDirComboBox.setStyleSheet("QComboBox{\n"
                                           "    height: 48px;\n"
                                           "    color: #cccccc;\n"
                                           "    font: 28px \"微软雅黑\";\n"
                                           "    border: 2px solid #4d4d4d;\n"
                                           "    border-radius: 12px;\n"
                                           "}\n"
                                           "\n"
                                           "QComboBox:hover{\n"
                                           "    border: 2px solid #8a8a8a;\n"
                                           "}\n"
                                           "\n"
                                           "QComboBox::drop-down{\n"
                                           "    border-image: url(:/icon/icon_resources/下拉箭头.svg);\n"
                                           "    width: 30px;\n"
                                           "    height: 30px;\n"
                                           "    margin-top: 9px;\n"
                                           "    margin-right: 10px;\n"
                                           "}\n"
                                           "\n"
                                           "QComboBox QAbstractItemView{\n"
                                           "    border: 2px solid #8a8a8a;\n"
                                           "    border-radius: 12px;\n"
                                           "    outline: none;\n"
                                           "    color: #cccccc;\n"
                                           "    font: 28px \"微软雅黑\";\n"
                                           "    background: #272626;\n"
                                           "    padding: 12px 6px 12px 6px;\n"
                                           "}\n"
                                           "\n"
                                           "QComboBox QAbstractItemView::item{\n"
                                           "    border: none;\n"
                                           "    outline: none;\n"
                                           "    height: 48px;\n"
                                           "    border-radius: 12px;\n"
                                           "    background: #272626;\n"
                                           "}\n"
                                           "QComboBox QAbstractItemView::item:selected{\n"
                                           "    border-radius: 12px;\n"
                                           "    background: #313131;\n"
                                           "}\n"
                                           "QComboBox QAbstractItemView::item:hover{\n"
                                           "    border-radius: 12px;\n"
                                           "    background: #4D4D4D;\n"
                                           "}")
        self.gameDirComboBox.setFrame(True)
        self.gameDirComboBox.setObjectName("gameDirComboBox")
        self.gameDirComboBox.addItem("")
        self.gameDirComboBox.addItem("")
        self.verticalLayout_12.addWidget(self.gameDirComboBox)
        self.dirErrorHint = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.dirErrorHint.setStyleSheet("\n"
                                        "    font: 16px \"微软雅黑\";\n"
                                        "    color: #99BDC3;\n"
                                        "    margin-left: 5px;")
        self.dirErrorHint.setText("")
        self.dirErrorHint.setObjectName("dirErrorHint")
        self.verticalLayout_12.addWidget(self.dirErrorHint)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem7)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_11.addWidget(self.scrollArea)
        self.saveSettings = QtWidgets.QPushButton(self.settings_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveSettings.sizePolicy().hasHeightForWidth())
        self.saveSettings.setSizePolicy(sizePolicy)
        self.saveSettings.setStyleSheet("QPushButton{\n"
                                        "    height: 50px;\n"
                                        "    width: 220px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border: 2px solid #4d4d4d;\n"
                                        "    font: 20px \"微软雅黑\";\n"
                                        "    color: #99BDC3;\n"
                                        "    margin-top: 10px;\n"
                                        "    margin-bottom: 20px;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:hover{\n"
                                        "    background: #4d4d4d;\n"
                                        "}\n"
                                        "\n"
                                        "QPushButton:pressed{\n"
                                        "    background: #3d3d3d\n"
                                        "}")
        self.saveSettings.setObjectName("saveSettings")
        self.verticalLayout_11.addWidget(self.saveSettings, 0, QtCore.Qt.AlignHCenter)
        self.contentStackedWidget.addWidget(self.settings_widget)
        self.verticalLayout_3.addWidget(self.contentStackedWidget)
        self.horizontalLayout_2.addWidget(self.content)
        self.verticalLayout.addWidget(self.widgetMain)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.contentStackedWidget.setCurrentIndex(0)
        self.chooseType.setCurrentIndex(0)
        self.minimizeButton.clicked.connect(MainWindow.showMinimized)  # type: ignore
        self.closeButton.clicked.connect(MainWindow.close)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "DAB"))
        self.label.setText(_translate("MainWindow", "概览"))
        self.killerTargetType.setItemText(0, _translate("MainWindow", "所有"))
        self.killerTargetType.setItemText(1, _translate("MainWindow", "祭品"))
        self.killerTargetType.setItemText(2, _translate("MainWindow", "配件"))
        self.searchKillerItem.setPlaceholderText(_translate("MainWindow", "搜索..."))
        self.killerChooseList.setSortingEnabled(False)
        self.chooseTargetHint.setText(
            _translate("MainWindow", "<html><head/><body><p>从左边拖拽物品以添加，拖回以删除</p></body></html>"))
        self.emptyTargetButtom.setText(_translate("MainWindow", "清空"))
        self.killerStart.setText(_translate("MainWindow", "Start"))
        self.killerStopHint.setText(_translate("MainWindow", "点击Start以开始"))
        self.chooseType.setTabText(self.chooseType.indexOf(self.killerTab), _translate("MainWindow", "杀手"))
        self.addSurvivorTarget.setText(_translate("MainWindow", "添加"))
        self.survivorStart.setText(_translate("MainWindow", "Start"))
        self.survivorStopHint.setText(_translate("MainWindow", "点击Start以开始"))
        self.chooseType.setTabText(self.chooseType.indexOf(self.survivorTab), _translate("MainWindow", "逃生者"))
        self.developingButton.setText(_translate("MainWindow", "这里什么也没有"))
        self.settings.setText(_translate("MainWindow", "设置"))
        self.label_2.setText(_translate("MainWindow", "游戏目录"))
        self.gameDirComboBox.setItemText(0, _translate("MainWindow", "自动识别目录："))
        self.gameDirComboBox.setItemText(1, _translate("MainWindow", "选择目录..."))
        self.saveSettings.setText(_translate("MainWindow", "保存"))


from . import guiresources

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
